# Generated by Django 4.1.7 on 2023-03-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_hotel_hotel_main_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="hotel_Main_Img",
            field=models.FileField(upload_to=""),
        ),
    ]
